
#FROM ubi8
FROM registry.access.redhat.com/ubi8@sha256:d85bc4ef93c70be9396f7079262da29ae1f2b69eeb999aae57a5ef8301576dca
RUN yum -y update
RUN yum -y install sudo procps-ng hostname vim-common file bc
RUN yum clean all
RUN chmod 0666 /etc/sudoers
### sed -i -e "s+^%wheel+##%wheel+" -e "s+^# %wheel+%wheel+" /etc/sudoers
RUN echo 'test ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN chmod 0440 /etc/sudoers
### useradd -G wheel -M test
RUN useradd -M -u 2000 test
CMD [ "/bin/bash" ]

